---
- hosts: all
  tasks:
  - name: modify /etc/hosts.allow
    lineinfile:
      path: /etc/hosts.allow
      line: telnet:192.168.0.:allow
      backup: yes
  - name: modify /etc/hosts.deny
    lineinfile:
      path: /etc/hosts.deny
      line: telnet:all:deny
      backup: yes
