---
- hosts: all
  tasks:
  - name: enable service ntpd and ensure it is not masked
    systemd:
      name: ntpd
      enabled: yes
      masked: no
  - name: copy ntpd service configuration
    copy:
      src: templates/ntp.conf
      dest: /etc/ntp.conf
      backup: yes
  - name: restart service ntpd on centos, in all cases, also issue daemon-reload to pick up config changes
    systemd:
      state: restarted
      daemon_reload: yes
      name: ntpd
