---
- hosts: all
  tasks:
  - name: set PermitRootLogin to no in /etc/ssh/sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin\ no'
      insertafter: '^#PermitRootLogin'
      line: PermitRootLogin no
      backup: yes
      #state: present
      state: absent
