---
- hosts: all
  tasks:
  - name: set TMOUT=180 in /etc/profile
    lineinfile:
      path: /etc/profile
      regexp: '^TMOUT'
      insertbefore: '^export\ PATH\ USER\ LOGNAME\ MAIL\ HOSTNAME\ HISTSIZE\ HISTCONTROL'
      line: TMOUT=180
      backup: yes
  - name: export TMOUT=180 in /etc/profile
    lineinfile:
      path: /etc/profile
      regexp: '^export\ PATH\ USER\ LOGNAME\ MAIL\ HOSTNAME\ HISTSIZE\ HISTCONTROL'
      line: export PATH USER LOGNAME MAIL HOSTNAME HISTSIZE HISTCONTROL TMOUT
      backup: yes
  - name: set umask 027
    lineinfile:
      path: templates/profile
      regexp: ''
