---
- hosts: all
  vars:
    acceptip: 222.212.89.53
  tasks:
  - name: add {{ acceptip }} to fw
    firewalld:
      rich_rule: rule family=ipv4 source address={{ acceptip }} accept
      zone: public
      permanent: yes
      state: enabled
      immediate: yes
