# jdk.yml
---
- hosts: all
  vars:
    jdk_file: file/jdk-8u301-linux-x64.tar.gz
    jdk_dest_dir: /data/thirdAssembly
    jdk_version: jdk1.8.0_301
  tasks:
  - name: Create {{ jdk_dest_dir }} directory if it does not exist
    file:
      path: "{{ jdk_dest_dir }}"
      state: directory
      mode: '0755'
      owner: webadmin
      group: webadmin
  - name: extract {{ jdk_file }} to {{ jdk_dest_dir }}
    unarchive:
      src: "{{ jdk_file }}"
      dest: "{{ jdk_dest_dir }}"
      remote_src: no
  - name: add file /etc/profile.d/java_env.sh
    file:
      path: /etc/profile.d/java_env.sh
      state: touch
      mode: '0755'
      owner: root
      group: root
  - name: add JAVA to /etc/profile.d/java_env.sh
    blockinfile:
      path: /etc/profile.d/java_env.sh
      block: |
        export JAVA_HOME={{ jdk_dest_dir }}/{{ jdk_version }}
        export PATH=$JAVA_HOME/bin/:$PATH
        export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
      marker: "# {mark} ANSIBLE MANAGED BLOCK FOR JAVA ENV"
