---
- hosts: all
  tasks:
    - name: check listen user
      user:
        name: listen
        state: absent
        remove: yes
    - name: check gdm user
      user:
        name: gdm
        shell: /sbin/nologin
        move_home: yes
        password_lock: yes
        state: present
    - name: check webservd user
      user:
        name: webservd
        state: absent
        remove: yes
    - name: check nobody user
      user:
        name: nobody
        shell: /sbin/nologin
        move_home: yes
        password_lock: yes
        state: present
    - name: check nobody4 user
      user:
        name: nobody4
        state: absent
        remove: yes
    - name: del noaccess user
      user:
        name: noaccess
        state: absent
        remove: yes
