- hosts: all
  remote_user: root
  gather_facts: false

  tasks:
  - name: modify /etc/hosts.allow
    lineinfile:
      path: /etc/hosts.allow
      line: telnet:39.130.228.:allow
      backup: yes
  - name: modify /etc/hosts.deny
    lineinfile:
      path: /etc/hosts.deny
      line: telnet:all:deny
      backup: yes
  - name: modify "password    sufficient    pam_unix.so"
    lineinfile:
      path: /etc/pam.d/system-auth
      regexp: '^password\ *sufficient\ *pam_unix.so'
      line: password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok remember=5
  - name: modify "password    requisite     pam_pwquality.so"
    lineinfile:
      path: /etc/pam.d/system-auth
      regexp: '^password\ *requisite\ *pam_pwquality.so'
      line: password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type= dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 minclass=2 minlen=8
      backup: yes
  #- name: add auth required pam_tally2.so deny=6 onerr=fail no_magic_root unlock_time=120
  #  lineinfile:
  #    path: /etc/pam.d/system-auth
  #    insertafter: '^auth\ *required\ *pam_env.so'
  #    line: auth        required      pam_tally2.so deny=6 onerr=fail no_magic_root unlock_time=120
  #    backup: yes
  - name: modify "/etc/login.defs"
    lineinfile:
      path: /etc/login.defs
      regexp: '^PASS_MIN_LEN\ *'
      line: PASS_MIN_LEN    8
      backup: yes
  - name: modify "/etc/ssh/sshd_config"
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      backup: yes
    with_items:
      - {regexp: '^PermitRootLogin\ *yes',line: 'PermitRootLogin no'}
      - {regexp: '^#PermitRootLogin',line: 'PermitRootLogin no'}
