- hosts: all
  remote_user: root
  gather_facts: false

  tasks:
  - name: modify "/etc/ssh/sshd_config add Ciphers, KexAlgorithms, MACs and Protocol version 2"
    blockinfile:
      path: /etc/ssh/sshd_config
      backup: yes
      marker: "# {mark} ANSIBLE MANAGED BLOCK FOR sshd_config"
      block: |
        Ciphers aes128-ctr,aes192-ctr,aes256-ctr
        KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
        MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com,hmac-sha1
        Protocol 2
