# redis cluster playbook
---
- hosts: 2021redis
  remote_user: root
  vars:
    redis_src_dir: /web/soft/redis-5.0.9
    redis_server: "{{ redis_src_dir }}/src/redis-server"
    redis_cluster_dir: /web/soft/redis_cluster
    redis_port_start: 6379
    redis_count: 2
  tasks:
 # - name: install os packages
 #   become: yes
 #   yum:
 #     name: [make, gcc]
 #     update_cache: yes
 # - name: clone redis git repo
 #   git:
 #     repo: https://github.com/antirez/redis.git
 #     dest: "{{ redis_src_dir }}"
 #     version: 5.0.9
 # - name: compile redis
 #   command: make
 #   args:
 #     chdir: "{{ redis_src_dir }}"
  - name: create cluster dirs
    file:
      path: "{{ redis_cluster_dir }}/{{ item }}"
      state: directory
    with_sequence: start={{ redis_port_start }} count={{ redis_count }}
  - name: copy redis-server to cluster dirs
    copy:
      remote_src: true
      src: "{{ redis_server }}"
      dest: "{{ redis_cluster_dir }}/{{ item }}/"
      mode: u+x
    with_sequence: start={{ redis_port_start }} count={{ redis_count }}
  - name: copy redis.conf to cluster dirs
    template:
      src: redis.conf.j2
      dest: "{{ redis_cluster_dir }}/{{ item }}/redis.conf"
    with_sequence: start={{ redis_port_start }} count={{ redis_count }}
  - name: create redis-cli symlink
    file:
      src: "{{ redis_src_dir }}/src/redis-cli"
      dest: /web/soft/redis-cli
      state: link
  - name: start redis-server
    command: ./redis-server redis.conf
    args:
      chdir: "{{ redis_cluster_dir }}/{{ item }}"
    with_sequence: start={{ redis_port_start }} count={{ redis_count }}
