# redis firewalld playbook
---
- hosts: redishost
  tasks:
  - name: firewalld | 6379-6380 tcp
    firewalld:
      zone: public
      rich_rule: rule family=ipv4 source address=1.1.2.0/25 port protocol=tcp port=6379-6380 accept
      permanent: yes
      state: enabled
      immediate: yes
  - name: firewalld | 16379-16380 tcp
    firewalld:
      zone: public
      rich_rule: rule family=ipv4 source address=1.1.2.0/25 port protocol=tcp port=16379-16380 accept
      permanent: yes
      state: enabled
      immediate: yes
